messaging:
  host: tcp://localhost:61616
  user: admin
  password: admin
  retry:
    delay: 2000
    maxRetryTime: 604800000
    attempts: 5

server:
  port: 8090


feign:
  client:
    config:
      default:
        loggerLevel: basic
        error-decoder: kerner1000.MyErrorDecoder

logging:
  level:
    root: info
    kerner1000: debug
